/**
 * Project-wide constants. Keep these centralised so behaviour is configurable
 * without grepping the codebase.
 */

export const APP_NAME = 'Market Pulse AI';
export const APP_VERSION = '0.1.0';

/** Asia/Kolkata is the only timezone the system reasons about. */
export const MARKET_TIMEZONE = 'Asia/Kolkata';

/** NSE regular market hours (IST). */
export const MARKET_OPEN_HHMM = '09:15';
export const MARKET_CLOSE_HHMM = '15:30';

/**
 * SEBI compliance disclaimer. Embedded at the bottom of every briefing and in
 * the README. Do NOT remove.
 */
export const SEBI_DISCLAIMER = [
  'This briefing is generated by Market Pulse AI for personal research only.',
  'It is not investment advice and is not a SEBI-registered research analyst product.',
  "All investment decisions are the recipient's sole responsibility.",
  'Do not redistribute. Do not automate order placement based on these signals.',
].join(' ');

/**
 * Default rate limits per data source (requests per second). Conservative on
 * purpose - exceeding these can get our IP soft-banned.
 */
export const RATE_LIMITS = {
  nse: 2,
  yahoo: 5,
  screener: 1,
  rss: 2,
} as const;

export type DataSourceName = keyof typeof RATE_LIMITS;
